In [1]:
#Task 1

In [2]:
import numpy as np

In [4]:
a=np.array([[1,4,7,8],[2,5,0,1]])

In [13]:
b=a.tolist()

In [15]:
print(b)

[[1, 4, 7, 8], [2, 5, 0, 1]]


In [16]:
#Task 2 

In [52]:
#Methode 1

In [18]:
a=np.array([[1,4,7,8],[2,5,0,1],[7,11,0,9]])

In [20]:
print(a)

[[ 1  4  7  8]
 [ 2  5  0  1]
 [ 7 11  0  9]]


In [51]:
x=0
summ=0
size=a.shape
nraws=size[0]
for x in range (0,nraws) :
    diag=a[x,x]
    summ=summ+diag
print(summ)


6


In [53]:
#Methode 2

In [58]:
b=a.trace()

In [60]:
print(b)

6


In [62]:
#Task 3

In [72]:
a =np.array([[1,2],[3,5]])

In [64]:
x=2

In [79]:
a[a>x]

array([3, 5])

In [80]:
#Methode 2

In [86]:
for i in range (0,2):
    for j in range (0,2):
        if a[i,j] > 2:
            print (a[i,j],">",x)

3 > 2
5 > 2


In [87]:
#Task 4

In [89]:
A=np.random.random((3,3))
B=np.random.random((3,3))

In [93]:
print ("A est",A)
print("B est",B)

A est [[0.33086143 0.41574635 0.74346001]
 [0.70659541 0.18672697 0.12952927]
 [0.99186003 0.50750341 0.31167106]]
B est [[0.09561442 0.9747727  0.56273558]
 [0.94659001 0.89238341 0.903993  ]
 [0.2555954  0.35287211 0.38504946]]


In [95]:
C=np.add(A,B)
print(C)

[[0.42647585 1.39051905 1.30619559]
 [1.65318542 1.07911038 1.03352226]
 [1.24745543 0.86037552 0.69672052]]


In [96]:
C=A+B    

In [98]:
#Task 5 

In [100]:
size=C.shape

In [105]:
nraws=size[0]
print(nraws)

3


In [110]:
import statistics
for i in range (0,nraws):
    moy= statistics.mean (C[i,:])
    print(moy)

AttributeError: module 'math' has no attribute 'mean'